<!DOCTYPE html>
<html>

<body>
	<table>
		<tr>
			<td colspan="2">
				<h3>Contact Information from contact us</h3>
			</td>
		</tr>
		<tr>
			<td>Date:4 Aug 2023</td>
			<td>
				<?= $data['aug4']; ?>
			</td>
		</tr>
		<tr>
			<td>Date: 18 Aug 2023</td>
			<td>
				<?= $data['aus18']; ?>
			</td>
		</tr>
		<tr>
			<td>Date:8 sep 2023</td>
			<td>
				<?= $data['sep8']; ?>
			</td>
		</tr>
		<tr>
			<td>Date: 24 sep 2023</td>
			<td>
				<?= $data['sep22']; ?>
			</td>
		</tr>

		<tr>
			<td>Tempo Traveller
				₹ 7,999/- :
			</td>
			<td>
				<?= $data['numberInput']; ?>
			</td>
		</tr>
		<tr>
			<td>RE Himalayan (Solo)
				₹ 19,999/- :
			</td>
			<td>
				<?= $data['numberInput1']; ?>
			</td>
		</tr>

		<tr>
			<td>Name</td>
			<td>
				<?= $data['name']; ?>
			</td>
		</tr>
		<tr>
			<td>contact</td>
			<td>
				<?= $data['contact']; ?>
			</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>

		<tr>
			<td>Message:</td>
			<td>
				<?= $data['message']; ?>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<h3>Contact Information from contact us</h3>
			</td>
		</tr>
		<tr>
			<td>Name:</td>
			<td>
				<?= $data['fullname']; ?>
			</td>
		</tr>

		<tr>
			<td>Email:</td>
			<td>
				<?= $data['useremail']; ?>
			</td>
		</tr>

		<tr>
			<td>Message:</td>
			<td>
				<?= $data['message']; ?>
			</td>
		</tr>
	</table>

</body>

</html>