<!DOCTYPE html>
<html>

<body>
	<div class="container">

		<div style=" text-align: center; margin-top: -40px;">
			<h3 style="color: #3da9fc;font-weight: 700;
	font-size: 30px;font-family: sans-serif;">KODAIKANAL TREK & CAMP</h3>
			<img src="https://www.roamers.in/assets/img/kodaikanal/Pine%20forest.jpg"
				style="height: 200px; width: 200px; object-fit: cover; border-radius: 5px;" alt="">
			<br>
			<span style="text-align:center;color: #3da9fc;font-weight: 700;
	font-size: 32px;font-family: math;">Hello
				<?= $data['username']; ?> !!
			</span>
			<br>
			<span style="text-align:center;color: #000;font-weight: 700;
	font-size: 20px;font-family: math; padding: 20px 40px 0 40px;">
				We are Glad to have you on board! Thank you for choosing us as your travel companion. Please find the
				booking details below!
			</span>

			<table style="padding: 20px 0 0 31%; text-align: justify;">
				<tr>
					<td>
						<span style="color:#3da9fc; font-size: 20px;
	font-family: sans-serif;">Booking Details :</span>
					</td>
				</tr>

				<tr>
					<td style=" color:black; font-weight: 700;font-family: math;"> Date of Travelling:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['traval-date']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;font-family: math;">Name:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['username']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;font-family: math;">Email:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['email']; ?>
					</td>
				</tr>

				<tr>
					<td style="color:black; font-weight: 700;font-family: math;">Phone No:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['contact']; ?>
					</td>
				</tr>

				<tr>
					<td style=" color:black; font-weight: 700;font-family: math;">D.O.B:
					</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['date']; ?>
					</td>
				</tr>


				<tr>
					<td style=" color:black; font-weight: 700;font-family: math;">Gender:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['gender']; ?>
					</td>
					<tr>
					<td style=" color:black; font-weight: 700;font-family: math;">Sharing Type:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['sharing']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;font-family: math;">Traveller count:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['count']; ?>
					</td>
				</tr>
				<tr>
					<td style="color:black; font-weight: 700;font-family: math;">Address1:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['address1']; ?>
					</td>
				</tr>

				<tr>
					<td style="color:black; font-weight: 700;font-family: math;">Address2:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['address2']; ?>
					</td>
				</tr>
				<tr>
					<td style="color:black; font-weight: 700;font-family: math;">City:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['city']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;font-family: math;">Pincode:</td>
					<td style=" color:black; font-weight: 500;font-family: Google Sans;">
						<?= $data['pincode']; ?>
					</td>
				</tr>


			</table>
			<br>
			<img style="height: 100px; width: 100px; object-fit: cover;"
				src="https://www.roamers.in/assets/img/Logo/Logo%20mark-01.png" alt="">
		</div>

	</div>


</body>

</html>