<!DOCTYPE html>
<html>

<body>
	<div class="container">

		<div style=" text-align: center; margin-top: -40px;">
			<h3 style="color: #3da9fc;font-weight: 700;font-size: 32px;"> Kodaikanal Trek & Camp</h3>
			<!-- <img src="https://www.roamers.in/assets/img/pondicherry/Media/paradise-beach.jpg" style="height: 200px; width: 200px; object-fit: cover; border-radius: 5px;" alt=""> -->
			<table style="padding: 0 0 0 31%; text-align: justify;">
				<tr>
					<td>
						<span style="color:#3da9fc; font-size: 20px;">Bookers Details :</span>
					</td>
				</tr>

				<tr>
					<td style=" color:black; font-weight: 700;"> Date of Travelling:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['traval-date']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;">Name:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['username']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;">Email:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['email']; ?>
					</td>
				</tr>

				<tr>
					<td style="color:black; font-weight: 700;">Phone No:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['contact']; ?>
					</td>
				</tr>

				<tr>
					<td style=" color:black; font-weight: 700;">D.O.B:
					</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['date']; ?>
					</td>
				</tr>


				<tr>
					<td style=" color:black; font-weight: 700;">Gender:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['gender']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;">Sharing Type:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['sharing']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;">Traveller count:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['count']; ?>
					</td>
				</tr>
				<tr>
					<td style="color:black; font-weight: 700;">Address1:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['address1']; ?>
					</td>
				</tr>

				<tr>
					<td style="color:black; font-weight: 700;">Address2:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['address2']; ?>
					</td>
				</tr>
				<tr>
					<td style="color:black; font-weight: 700;">City:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['city']; ?>
					</td>
				</tr>
				<tr>
					<td style=" color:black; font-weight: 700;">Pincode:</td>
					<td style=" color:black; font-weight: 500;">
						<?= $data['pincode']; ?>
					</td>
				</tr>

			</table>
		</div>

	</div>


</body>

</html>