<!DOCTYPE html>
<html>

<body>
	<table>
		<tr>
			<td colspan="2">
				<h3>  Wonders of Wayanad</h3>
			</td>
		</tr>
		<tr>
			<td> Date of Travelling</td>
			<td>
				<?= $data['traval-date']; ?>
			</td>
		</tr>
		<tr>
			<td>Name</td>
			<td>
				<?= $data['username']; ?>
			</td>
		</tr>
		<tr>
			<td>Email</td>
			<td>
				<?= $data['email']; ?>
			</td>
		</tr>

		<tr>
			<td>Phone No</td>
			<td>
				<?= $data['contact']; ?>
			</td>
		</tr>

		<tr>
			<td>D.O.B
			</td>
			<td>
				<?= $data['date']; ?>
			</td>
		</tr>


		<tr>
			<td>Gender</td>
			<td>
				<?= $data['gender']; ?>
			</td>
		</tr>
		<tr>
			<td>sharing</td>
			<td>
				<?= $data['sharing']; ?>
			</td>
		</tr>
		<tr>
			<td>Pickup & Drop</td>
			<td>
				<?= $data['pickdrop']; ?>
			</td>
		</tr>
		<tr>
			<td>Traveller count</td>
			<td>
				<?= $data['count']; ?>
			</td>
		</tr>
		<tr>
			<td>Address1</td>
			<td>
				<?= $data['address1']; ?>
			</td>
		</tr>

		<tr>
			<td>Address2</td>
			<td>
				<?= $data['address2']; ?>
			</td>
		</tr>
		<tr>
			<td>City</td>
			<td>
				<?= $data['city']; ?>
			</td>
		</tr>
		<tr>
			<td>Pincode</td>
			<td>
				<?= $data['pincode']; ?>
			</td>
		</tr>

	</table>

</body>

</html>