<!DOCTYPE html>
<html>

<body>
	<table>
		<tr>
			<td colspan="2">
				<h3>Enquery from Roamers Website:</h3>
			</td>
		</tr>
		<tr>
			<td>Name :</td>
			<td>
				<?= $data['name1']; ?>
			</td>
		</tr>
		<tr>
			<td>Email :</td>
			<td>
				<?= $data['email1']; ?>
			</td>
		</tr>
		<tr>
			<td>Phone No:
			</td>
			<td>
				<?= $data['phone1']; ?>
			</td>
		</tr>

		<tr>
			<td>Destination :
			</td>
			<td>
				<?= $data['des']; ?>
			</td>
		</tr>
		<tr>
			<td>Message :
			</td>
			<td>
				<?= $data['mess']; ?>
			</td>
		</tr>
	</table>

</body>

</html>